/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Operaciones.Listas;
import javax.swing.JOptionPane;

public class VistaPlantilla extends javax.swing.JFrame {

    Listas opb = new Listas();

    public VistaPlantilla() {
        initComponents();
        this.actualizarBotones(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipo = new javax.swing.ButtonGroup();
        btnGroupForma = new javax.swing.ButtonGroup();
        btnGroupBusqueda = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnInsertarFrente = new javax.swing.JButton();
        btnInsertarFinal = new javax.swing.JButton();
        btnInsertarDondesesa = new javax.swing.JButton();
        btnEliminarFinal = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnEliminarFrente = new javax.swing.JButton();
        btnEliminarDondesea = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        txtDato = new javax.swing.JTextField();
        txtAnterior = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlOrden = new javax.swing.JPanel();
        rbnBurbuja = new javax.swing.JRadioButton();
        rbnBurbujaMejorada = new javax.swing.JRadioButton();
        rbnMerge = new javax.swing.JRadioButton();
        rbnQuickSort = new javax.swing.JRadioButton();
        rbnShell = new javax.swing.JRadioButton();
        pnlSentidoOrden = new javax.swing.JPanel();
        rbnAsc = new javax.swing.JRadioButton();
        rbnDesc = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operaciones de Listas simples", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 0, 102))); // NOI18N

        btnInsertarFrente.setText("Insertar al frente");
        btnInsertarFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarFrenteActionPerformed(evt);
            }
        });

        btnInsertarFinal.setText("Insertar al final");
        btnInsertarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarFinalActionPerformed(evt);
            }
        });

        btnInsertarDondesesa.setText("Insertar en cualquier lugar");
        btnInsertarDondesesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarDondesesaActionPerformed(evt);
            }
        });

        btnEliminarFinal.setText("Eliminar al final");
        btnEliminarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFinalActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnEliminarFrente.setText("Eliminar al frente");
        btnEliminarFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFrenteActionPerformed(evt);
            }
        });

        btnEliminarDondesea.setText("Eliminar en cualquier lugar");
        btnEliminarDondesea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDondeseaActionPerformed(evt);
            }
        });

        btnOrdenar.setText("Ordenar");
        btnOrdenar.setName(""); // NOI18N
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.setName(""); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsertarFrente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsertarFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsertarDondesesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarDondesea, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarFrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnInsertarFrente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsertarFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsertarDondesesa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarDondesea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrdenar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addGap(22, 22, 22))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad de columnas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 0, 102))); // NOI18N

        txtDato.setEnabled(false);
        txtDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatoActionPerformed(evt);
            }
        });

        txtAnterior.setEnabled(false);
        txtAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnteriorActionPerformed(evt);
            }
        });

        jLabel1.setText("Dato");

        jLabel2.setText("Elemento anterior");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlOrden.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de ordenamiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        btnGroupTipo.add(rbnBurbuja);
        rbnBurbuja.setSelected(true);
        rbnBurbuja.setText("Burbuja");

        btnGroupTipo.add(rbnBurbujaMejorada);
        rbnBurbujaMejorada.setText("Burbuja mejorada");

        btnGroupTipo.add(rbnMerge);
        rbnMerge.setText("Merge");

        btnGroupTipo.add(rbnQuickSort);
        rbnQuickSort.setText("Quick sort");

        btnGroupTipo.add(rbnShell);
        rbnShell.setText("Shell");

        javax.swing.GroupLayout pnlOrdenLayout = new javax.swing.GroupLayout(pnlOrden);
        pnlOrden.setLayout(pnlOrdenLayout);
        pnlOrdenLayout.setHorizontalGroup(
            pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOrdenLayout.createSequentialGroup()
                        .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbnBurbuja)
                            .addComponent(rbnBurbujaMejorada))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(pnlOrdenLayout.createSequentialGroup()
                        .addGroup(pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbnMerge)
                            .addComponent(rbnQuickSort)
                            .addComponent(rbnShell))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlOrdenLayout.setVerticalGroup(
            pnlOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbnBurbuja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbnBurbujaMejorada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbnMerge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbnShell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbnQuickSort)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pnlSentidoOrden.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Forma de ordenamiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        btnGroupForma.add(rbnAsc);
        rbnAsc.setSelected(true);
        rbnAsc.setText("Ascendente");

        btnGroupForma.add(rbnDesc);
        rbnDesc.setText("Descendente");

        javax.swing.GroupLayout pnlSentidoOrdenLayout = new javax.swing.GroupLayout(pnlSentidoOrden);
        pnlSentidoOrden.setLayout(pnlSentidoOrdenLayout);
        pnlSentidoOrdenLayout.setHorizontalGroup(
            pnlSentidoOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSentidoOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSentidoOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbnAsc)
                    .addComponent(rbnDesc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSentidoOrdenLayout.setVerticalGroup(
            pnlSentidoOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSentidoOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbnAsc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbnDesc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSentidoOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(pnlSentidoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void txtDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatoActionPerformed
    boolean flag = false;
    boolean click = false;
    private void btnInsertarFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarFrenteActionPerformed
        if (!click) {
            txtDato.setEnabled(!click);
            click = true;
        } else {

            if (!txtDato.getText().equals("")) {
                try {
                    double dato = Double.parseDouble(txtDato.getText());
                    opb.insertarAlFrente(dato);
                    if (flag == false) {
                        flag = true;
                        actualizarBotones(flag);
                    }
                    txtDato.setEnabled(!click);
                    click = false;
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Ingrese valores numéricos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios");
            }
        }
    }//GEN-LAST:event_btnInsertarFrenteActionPerformed

    private void btnInsertarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarFinalActionPerformed
        if (!click) {
            txtDato.setEnabled(!click);
            click = true;
        } else {
            txtDato.setEnabled(true);
            if (!txtDato.getText().equals("")) {
                try {
                    double dato = Double.parseDouble(txtDato.getText());
                    opb.ingresarAlUltimo(dato);
                    if (flag == false) {
                        flag = true;
                        actualizarBotones(flag);
                    }
                    txtDato.setEnabled(!click);
                    click = false;
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Ingrese valores numéricos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios");
            }
        }
    }//GEN-LAST:event_btnInsertarFinalActionPerformed

    private void btnInsertarDondesesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarDondesesaActionPerformed
        if (!click) {
            txtDato.setEnabled(!click);
            txtAnterior.setEnabled(!click);
            click = true;
        } else {
            if (!txtDato.getText().equals("") || !txtAnterior.getText().equals("")) {
                try {
                    double anterior = Double.parseDouble(txtAnterior.getText());
                    double dato = Double.parseDouble(txtDato.getText());
                    opb.insertearDondeSea(anterior, dato);
                    txtDato.setEnabled(!click);
                    txtAnterior.setEnabled(!click);
                    click = false;
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Ingrese valores numéricos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios");
            }
        }
    }//GEN-LAST:event_btnInsertarDondesesaActionPerformed

    private void btnEliminarFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFrenteActionPerformed
        opb.eliminarAlFrente();
    }//GEN-LAST:event_btnEliminarFrenteActionPerformed

    private void btnEliminarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFinalActionPerformed
        opb.eliminarAlFinal();
    }//GEN-LAST:event_btnEliminarFinalActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        txtResultado.setText(opb.imprimir());
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnEliminarDondeseaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDondeseaActionPerformed
        if (!click) {
            txtDato.setEnabled(!click);
            click = true;
        } else {
            txtDato.setEnabled(true);
            if (!txtDato.getText().equals("")) {
                try {
                    double dato = Double.parseDouble(txtDato.getText());
                    opb.eliminarDondeSea(dato);
                    txtDato.setEnabled(!click);
                    click = false;
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Ingrese valores numéricos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El campo no pueden estar vacios");
            }
        }
    }//GEN-LAST:event_btnEliminarDondeseaActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        if (rbnBurbuja.isSelected() && rbnAsc.isSelected()) {
            opb.ordenBurbujaAscendente();
            txtResultado.setText("Ordenado por el método Burbuja de forma ascendente\n" + opb.imprimir());
        }
        if (rbnBurbuja.isSelected() && rbnDesc.isSelected()) {
            opb.ordenBurbujaDescendente();
            txtResultado.setText("Ordenado por el método Burbuja de forma descendente\n" + opb.imprimir());
        }
        if (rbnBurbujaMejorada.isSelected() && rbnAsc.isSelected()) {
            opb.ordenBurbujaAscendenteMejorado();
            txtResultado.setText("Ordenado por el método Burbuja mejorada de forma ascendente\n" + opb.imprimir());
        }
        if (rbnBurbujaMejorada.isSelected() && rbnDesc.isSelected()) {
            opb.ordenBurbujaDescendentemejorado();
            txtResultado.setText("Ordenado por el método Burbuja mejorada de forma descendente\n" + opb.imprimir());
        }
        if (rbnMerge.isSelected() && rbnAsc.isSelected()) {
            opb.ordenMergeAscendente();
            txtResultado.setText("Ordenado por el método Merge de forma ascendente\n" + opb.imprimir());
        }
        if (rbnMerge.isSelected() && rbnDesc.isSelected()) {
            opb.ordenMergeDescendente();
            txtResultado.setText("Ordenado por el método Merge de forma descendente\n" + opb.imprimir());
        }
        if (rbnShell.isSelected() && rbnAsc.isSelected()) {
            opb.ordenShellAscendente();
            txtResultado.setText("Ordenado por el método Shell de forma ascendente\n" + opb.imprimir());
        }
        if (rbnShell.isSelected() && rbnDesc.isSelected()) {
            opb.ordenShellDescendente();
            txtResultado.setText("Ordenado por el método Shell de forma descendente\n" + opb.imprimir());
        }
        if (rbnQuickSort.isSelected() && rbnAsc.isSelected()) {
            opb.ordenQuickSortAscendente();
            txtResultado.setText("Ordenado por el método Quick de forma ascendente\n" + opb.imprimir());
        }
        if (rbnQuickSort.isSelected() && rbnDesc.isSelected()) {
            opb.ordenQuickSortDescendente();
            txtResultado.setText("Ordenado por el método Quick de forma descendente\n" + opb.imprimir());
        }
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!click) {
            txtDato.setEnabled(!click);
            click = true;
        } else {
            if (!txtDato.getText().equals("")) {
                try {
                    double dato = Double.parseDouble(txtDato.getText());
                    txtResultado.setText(opb.busquedaSecuencial(dato));
                    txtDato.setEnabled(!click);
                    click = false;
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Ingrese valores numéricos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El campo no pueden estar vacios");
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnteriorActionPerformed

    private void actualizarBotones(boolean estado) {
        btnInsertarDondesesa.setEnabled(estado);
        btnEliminarFrente.setEnabled(estado);
        btnEliminarFinal.setEnabled(estado);
        btnEliminarDondesea.setEnabled(estado);
        btnImprimir.setEnabled(estado);
        btnBuscar.setEnabled(estado);
        btnOrdenar.setEnabled(estado);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPlantilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarDondesea;
    private javax.swing.JButton btnEliminarFinal;
    private javax.swing.JButton btnEliminarFrente;
    private javax.swing.ButtonGroup btnGroupBusqueda;
    private javax.swing.ButtonGroup btnGroupForma;
    private javax.swing.ButtonGroup btnGroupTipo;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnInsertarDondesesa;
    private javax.swing.JButton btnInsertarFinal;
    private javax.swing.JButton btnInsertarFrente;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlOrden;
    private javax.swing.JPanel pnlSentidoOrden;
    private javax.swing.JRadioButton rbnAsc;
    private javax.swing.JRadioButton rbnBurbuja;
    private javax.swing.JRadioButton rbnBurbujaMejorada;
    private javax.swing.JRadioButton rbnDesc;
    private javax.swing.JRadioButton rbnMerge;
    private javax.swing.JRadioButton rbnQuickSort;
    private javax.swing.JRadioButton rbnShell;
    private javax.swing.JTextField txtAnterior;
    private javax.swing.JTextField txtDato;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
